apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: servebc-api
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  CORS_ORIGIN: "{{ .Values.corsOrigin }}"
  API_PORT: "{{ .Values.containerPorts.http }}"
  NODE_ENV: "{{ .Values.nodeEnv }}"
  LOG_LEVEL: "{{ .Values.logLevel }}"
