{{- if and .Values.database.initJob.enabled .Values.database.usePostgres }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-db-init
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}
  DB_NAME: {{ .Values.database.dbName }}
  DB_HOST: {{ .Values.database.host }}
  DB_PORT: "{{ .Values.database.port }}"
{{- end }}
